from django.contrib import admin
from .models import PNF, Trayecto, Tramo, Materia, Seccion, Inscripcion, Calificacion, Horario, SolicitudConstancia, Reporte, Actividad, Notificacion, SolicitudCambioSeccion, AsignacionDocente, Asistencia, ConfiguracionUsuario, PeriodoAcademico, Evento, Foro, ComentarioForo, HistorialAcademico

admin.site.register(PNF)
admin.site.register(Trayecto)
admin.site.register(Tramo)
admin.site.register(Materia)
admin.site.register(Seccion)
admin.site.register(Inscripcion)
admin.site.register(Calificacion)
admin.site.register(Horario)
admin.site.register(SolicitudConstancia)
admin.site.register(Reporte)
admin.site.register(Actividad)
admin.site.register(Notificacion)
admin.site.register(SolicitudCambioSeccion)
admin.site.register(AsignacionDocente)
admin.site.register(Asistencia)
admin.site.register(ConfiguracionUsuario)
admin.site.register(PeriodoAcademico)
admin.site.register(Evento)
admin.site.register(Foro)
admin.site.register(ComentarioForo)
admin.site.register(HistorialAcademico)
