# Generated by Django 5.2.5 on 2025-09-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Programa Nacional de Formación')),
                ('sede', models.CharField(max_length=50, verbose_name='Sede')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='pnf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.pnf', verbose_name='Oferta Académica'),
        ),
    ]
