# Generated by Django 5.2.5 on 2025-09-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
