# Generated by Django 5.2.5 on 2025-09-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usuario_apellido_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Usuario'),
        ),
    ]
