# Generated by Django 5.2.5 on 2025-09-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('personal', 'Personal Administrativo')], default='estudiante', max_length=20, verbose_name='Rol'),
        ),
    ]
