# Generated by Django 5.2.5 on 2025-09-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_visible',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Clave Visible'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('coordinador', 'Coordinador'), ('personal', 'Personal Administrativo'), ('jefe', 'Jefe de Control de Estudios')], default='estudiante', max_length=20, verbose_name='Rol'),
        ),
    ]
